### PR TITLE
Updated all the logos to indigo versions

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
I've updated all the logos from their old green versions to the new indigo version. But the logos were hosted from `https://s3.amazonaws.com/freecodecamp/favicons/` so I added the new logos in the `favicons` folder. (I've also update the `index.html` accordingly)

### CODE REVIEW

**Comment by Twaha-Rahman** [comment]
I don't know the size of the logos referenced on the lines 138 to 145 in `index.html`. Can anybody confirm the size?

```
    <link
      href="https://s3.amazonaws.com/freecodecamp/favicons/apple-touch-icon-precomposed.png"
      rel="apple-touch-icon-precomposed"
    />
    <link
      href="https://s3.amazonaws.com/freecodecamp/favicons/apple-touch-icon.png"
      rel="apple-touch-icon"
    />
```

**Comment by Twaha-Rahman** [comment]
Lemme know if I need to change or update anything ;)

**Comment by moT01** [comment]
I'm not sure if we want to add the images directly to the repo. These images must be already hosted on amazon for us.

**Comment by Twaha-Rahman** [comment]
@moT01  So how would you like to proceed?

**Comment by moT01** [comment]
@ahmadabdolsaheb, maybe you can shed some light on the best way here.

**Comment by Twaha-Rahman** [comment]
@moT01 Any progress on the PR?

**Comment by ahmaxed** [comment]
I believe we should just keep the favicons centralized and serve them from s3, that way we would only have to change s3 bucket when we need to make changes across our platforms.

Thank you for the PR. I will see if I can use favicons from this pr to update the S3 bucket.

**Pull request closed without merging**
