### PR TITLE
Remove GitHub Configuration Files

### PR DESCRIPTION
**Pull request by thatrobotdev**
Removes multiple leftover .DS_Store files.

### CODE REVIEW

**Review by johnkennedy9147 — APPROVED** [review]
@jamesjpk123 LGTM, thanks for your contribution

**Comment by johnkennedy9147** [comment]
@QuincyLarson 
I've not merged this as I haven't worked on this repo before and don't have time just now for a deeper dive.  raised #24 to add .gitignore to prevent future contributors accidentally adding these files

**Comment by QuincyLarson** [comment]
@jamesjpk123 Thanks for cleaning up these files! Merged.

**Comment by QuincyLarson** [comment]
@johnkennedy9147 Thanks for raising that other PR to help people avoid accidentally committing these files. I've merged it, too.

**Pull request merged**
