### PR TITLE
Pull-Request: Add Night Mode page to design-style-guide

### PR DESCRIPTION
**Pull request by tommygebru**

### CODE REVIEW

**Comment by raisedadead** [comment]
Do we want this? I am not convinced why we should be adding "Night Mode" which is a just feature on the main website to our branding guidelines which has a larger scope.

To me this is not a fit to this guidelines.

/cc @QuincyLarson

**Comment by tommygebru** [comment]
@raisedadead I am only attempting this because I was requested to do so my a Member either here on Github or Gitter, I will try to find the conversation, screenshot and send to you.

Also- if it seems too prominent to make Night mode its own page, perhaps it would be better to make it less visible and display it within the Brand Colors page?

Also- I am not sure that freeCodeCamp uses all of the colors Primary & Secondary... should we trim?

**Comment by tommygebru** [comment]
screen shot 2017-01-29 at 8 19 06 am
screen shot 2017-01-29 at 8 22 45 am
screen shot 2017-01-29 at 8 25 06 am

**Comment by raisedadead** [comment]
Thanks @tommygebru for the screenshots but that conversation in no way is conclusive or decisive if we "really" want to add this to our branding guidelines. So, once again the question remains:

> why we should be adding "Night Mode" which is a just feature on the main website to our branding guidelines which has a larger scope.

**Comment by ghost** [comment]
I don't believe this should be added. The dark mode is more of a theme, rather than apart of the branding guidelines.

**Comment by QuincyLarson** [comment]
@tommygebru I agree with @atjonathan and @raisedadead that at this time we don't need a night mode background color. If you have design ability, we do have a ton of things we need help with over at https://github.com/FreeCodeCamp/assets/issues though :)

**Pull request closed without merging**
